sonar.organization=tppe-2026-1-marketplace
sonar.projectKey=TPPE-2026-1-Marketplace_MarketPlace-Backend
sonar.projectName=MarketPlace-Backend

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.integration.ts
sonar.exclusions=**/*.spec.ts,**/*.integration.ts,**/migrations/**
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
